In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import glob
import re

ruta = "/content/drive/MyDrive/ProyectoAnálisis/*.csv"
files = glob.glob(ruta)

dataframes = []

for file in files:
    df = pd.read_csv(file)

    # extraer año del nombre del archivo
    year = re.search(r'\d{4}', file).group()
    df["year"] = int(year)

    dataframes.append(df)

print(f"Se cargaron {len(dataframes)} datasets.")

/tmp/ipykernel_285/1518428597.py:11: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_285/1518428597.py:11: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_285/1518428597.py:11: DtypeWarning: Columns (81,82,83,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)
/tmp/ipykernel_285/1518428597.py:11: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Se cargaron 10 datasets.

In [ ]:
#Busqueda de columnas diferentes
todas_columnas = set()

for df in dataframes:
    todas_columnas.update(df.columns)

print("Total columnas diferentes encontradas:", len(todas_columnas))

for col in sorted(todas_columnas):
    print(col)

Total columnas diferentes encontradas: 159
Acceleration
Age
Aggression
Agility
Att work rate
Balance
Ball
Club
Composure
Crossing
Curve
Def
Def work rate
Defending
Dribbling
Finishing
Free
GK
Gender
Heading
Interceptions
Jumping
Long
Name
Nation
Overall
Pace
Passing
Penalties
Physicality
Position
Positioning
Preferred foot
Reactions
Shooting
Shot
Skill moves
Sliding
Sprint
Stamina
Standing
Strength
URL
Unnamed: 0
Vision
Volleys
Weak foot
Year
age
attacking_crossing
attacking_finishing
attacking_heading_accuracy
attacking_short_passing
attacking_volleys
body_type
cam
cb
cdm
cf
club_contract_valid_until
club_flag_url
club_jersey_number
club_joined
club_loaned_from
club_logo_url
club_name
club_position
club_team_id
cm
defending
defending_marking_awareness
defending_sliding_tackle
defending_standing_tackle
dob
dribbling
gk
goalkeeping_diving
goalkeeping_handling
goalkeeping_kicking
goalkeeping_positioning
goalkeeping_reflexes
goalkeeping_speed
height_cm
international_reputation
lam
lb
lcb
lcm
ldm
league_level
league_name
lf
lm
long_name
ls
lw
lwb
mentality_aggression
mentality_composure
mentality_interceptions
mentality_penalties
mentality_positioning
mentality_vision
movement_acceleration
movement_agility
movement_balance
movement_reactions
movement_sprint_speed
nation_flag_url
nation_jersey_number
nation_logo_url
nation_position
nation_team_id
nationality_id
nationality_name
overall
pace
passing
physic
player_face_url
player_positions
player_tags
player_traits
player_url
potential
power_jumping
power_long_shots
power_shot_power
power_stamina
power_strength
preferred_foot
ram
rb
rcb
rcm
rdm
real_face
release_clause_eur
rf
rm
rs
rw
rwb
shooting
short_name
skill_ball_control
skill_curve
skill_dribbling
skill_fk_accuracy
skill_long_passing
skill_moves
sofifa_id
st
value_eur
wage_eur
weak_foot
weight_kg
work_rate
year

In [ ]:
for df in dataframes:
    print("year:", df["year"].iloc[0])
    print(len(df.columns), "columnas")
    print(df.columns.tolist())
    print()

year: 2015
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2016
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2017
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2018
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2019
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2020
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2021
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2022
111 columnas
['sofifa_id', 'player_url', 'short_name', 'long_name', 'player_positions', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'dob', 'height_cm', 'weight_kg', 'club_team_id', 'club_name', 'league_name', 'league_level', 'club_position', 'club_jersey_number', 'club_loaned_from', 'club_joined', 'club_contract_valid_until', 'nationality_id', 'nationality_name', 'nation_team_id', 'nation_position', 'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves', 'international_reputation', 'work_rate', 'body_type', 'real_face', 'release_clause_eur', 'player_tags', 'player_traits', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic', 'attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking_awareness', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'player_face_url', 'club_logo_url', 'club_flag_url', 'nation_logo_url', 'nation_flag_url', 'year']

year: 2024
48 columnas
['Unnamed: 0', 'Name', 'Nation', 'Club', 'Position', 'Age', 'Overall', 'Pace', 'Shooting', 'Passing', 'Dribbling', 'Defending', 'Physicality', 'Acceleration', 'Sprint', 'Positioning', 'Finishing', 'Shot', 'Long', 'Volleys', 'Penalties', 'Vision', 'Crossing', 'Free', 'Curve', 'Agility', 'Balance', 'Reactions', 'Ball', 'Composure', 'Interceptions', 'Heading', 'Def', 'Standing', 'Sliding', 'Jumping', 'Stamina', 'Strength', 'Aggression', 'Att work rate', 'Def work rate', 'Preferred foot', 'Weak foot', 'Skill moves', 'URL', 'Gender', 'GK', 'year']

year: 2023
27 columnas
['Name', 'Position', 'overall', 'potential', 'value_eur', 'wage_eur', 'age', 'height_cm', 'weight_kg', 'league_name', 'league_level', 'Club', 'Nation', 'preferred_foot', 'weak_foot', 'skill_moves', 'pace', 'shooting', 'passing', 'dribbling', 'defending', 'Physicality', 'movement_acceleration', 'movement_sprint_speed', 'power_stamina', 'Year', 'year']

In [ ]:
for i in range(len(dataframes)):
  # Check if the 'Year' column exists in the current dataframe
  if "Year" in dataframes[i].columns:
    # If it exists, drop it and update the dataframe in the list
    dataframes[i] = dataframes[i].drop(columns=["Year"])

In [ ]:
#Renombrado de columnas
rename_dict = {

# nombres
"short_name": "name",
"Name": "name",

# posición
"player_positions": "position",
"Position": "position",

# overall
"Overall": "overall",

# club
"club_name": "club",
"Club": "club",

# nación
"nationality_name": "nation",
"Nation": "nation",

# físico
"physic": "physicality",
"Physicality": "physicality",

# edad
"Age": "age",

# pace
"Pace": "pace",

# shooting
"Shooting": "shooting",

# passing
"Passing": "passing",

# dribbling
"Dribbling": "dribbling",

# defending
"Defending": "defending",

# weak foot
"Weak foot": "weak_foot",

# preferred foot
"Preferred foot": "preferred_foot",

# skill moves
"Skill moves": "skill_moves",

# aceleración
"Acceleration": "movement_acceleration",

# sprint
"Sprint": "movement_sprint_speed",

# stamina
"Stamina": "power_stamina",

# year
"Year": "year"
}

for i in range(len(dataframes)):
    dataframes[i] = dataframes[i].rename(columns=rename_dict)

In [ ]:
#Selección de columnas finales para cada .csv
columnas_finales = [
"name",
"position",
"overall",
"potential",
"value_eur",
"wage_eur",
"age",
"height_cm",
"weight_kg",
"league_name",
"league_level",
"club",
"nation",
"preferred_foot",
"weak_foot",
"skill_moves",
"pace",
"shooting",
"passing",
"dribbling",
"defending",
"physicality",
"movement_acceleration",
"movement_sprint_speed",
"power_stamina",
"year"
]

for df in dataframes:

    y = df["year"].iloc[0]

    faltantes = [c for c in columnas_finales if c not in df.columns]

    if faltantes:
        print(f"Año {y} le faltan columnas:")
        print(faltantes)
        print()

Año 2024 le faltan columnas:
['potential', 'value_eur', 'wage_eur', 'height_cm', 'weight_kg', 'league_name', 'league_level']

In [ ]:
#Colocar las columnas faltantes y rellenarlo de nulos

for i in range(len(dataframes)):

    for col in columnas_finales:
        if col not in dataframes[i].columns:
            dataframes[i][col] = pd.NA

In [ ]:
#Seleccionar solo las columnas finales para cada .csv
for i in range(len(dataframes)):
    dataframes[i] = dataframes[i][columnas_finales]

In [ ]:
#Impurnar datos al 2024
#Limpieza nulos y duplicados
#Agregar columna de region con chat

In [ ]:
#Unir los 9 csv
df_total = pd.concat(dataframes, ignore_index=True)

print("Shape del dataset final:", df_total.shape)

df_total.info()

df_total.head()

/tmp/ipykernel_285/3899444425.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_total = pd.concat(dataframes, ignore_index=True)

Shape del dataset final: (324598, 26)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324598 entries, 0 to 324597
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   name                   324598 non-null  object
 1   position               324598 non-null  object
 2   overall                324598 non-null  int64
 3   potential              308753 non-null  object
 4   value_eur              306036 non-null  float64
 5   wage_eur               306405 non-null  float64
 6   age                    324598 non-null  int64
 7   height_cm              308753 non-null  object
 8   weight_kg              308753 non-null  object
 9   league_name            306397 non-null  object
 10  league_level           306012 non-null  float64
 11  club                   322242 non-null  object
 12  nation                 324598 non-null  object
 13  preferred_foot         324598 non-null  object
 14  weak_foot              324598 non-null  int64
 15  skill_moves            324598 non-null  int64
 16  pace                   290201 non-null  float64
 17  shooting               290201 non-null  float64
 18  passing                290201 non-null  float64
 19  dribbling              290201 non-null  float64
 20  defending              290201 non-null  float64
 21  physicality            290201 non-null  float64
 22  movement_acceleration  324598 non-null  int64
 23  movement_sprint_speed  324598 non-null  int64
 24  power_stamina          324598 non-null  int64
 25  year                   324598 non-null  int64
dtypes: float64(9), int64(8), object(9)
memory usage: 64.4+ MB

,name,position,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,league_name,...,pace,shooting,passing,dribbling,defending,physicality,movement_acceleration,movement_sprint_speed,power_stamina,year
0,L. Messi,CF,93,95,100500000.0,550000.0,27,169,67,Spain Primera Division,...,93.0,89.0,86.0,96.0,27.0,63.0,96,90,77,2015
1,Cristiano Ronaldo,"LW, LM",92,92,79000000.0,375000.0,29,185,80,Spain Primera Division,...,93.0,93.0,81.0,91.0,32.0,79.0,91,94,89,2015
2,A. Robben,"RM, LM, RW",90,90,54500000.0,275000.0,30,180,80,German 1. Bundesliga,...,93.0,86.0,83.0,92.0,32.0,64.0,93,93,78,2015
3,Z. Ibrahimović,ST,90,90,52500000.0,275000.0,32,195,95,French Ligue 1,...,76.0,91.0,81.0,86.0,34.0,86.0,74,77,78,2015
4,M. Neuer,GK,90,90,63500000.0,300000.0,28,193,92,German 1. Bundesliga,...,NaN,NaN,NaN,NaN,NaN,NaN,58,61,44,2015

In [ ]:
#Tipado

# columnas categóricas
categoricas = [
"name",
"position",
"league_name",
"club",
"nation",
"preferred_foot"
]

# columnas enteras
enteras = [
"overall",
"potential",
"age",
"height_cm",
"weight_kg",
"weak_foot",
"skill_moves",
"pace",
"shooting",
"passing",
"dribbling",
"defending",
"physicality",
"movement_acceleration",
"movement_sprint_speed",
"power_stamina",
"league_level",
"year"
]

# columnas float
floats = [
"value_eur",
"wage_eur"
]

# aplicar tipado
df_total[categoricas] = df_total[categoricas].astype("category")
df_total[enteras] = df_total[enteras].astype("Int64")
df_total[floats] = df_total[floats].astype("float")

df_total.dtypes

name                     category
position                 category
overall                     Int64
potential                   Int64
value_eur                 float64
wage_eur                  float64
age                         Int64
height_cm                   Int64
weight_kg                   Int64
league_name              category
league_level                Int64
club                     category
nation                   category
preferred_foot           category
weak_foot                   Int64
skill_moves                 Int64
pace                        Int64
shooting                    Int64
passing                     Int64
dribbling                   Int64
defending                   Int64
physicality                 Int64
movement_acceleration       Int64
movement_sprint_speed       Int64
power_stamina               Int64
year                        Int64
dtype: object

In [ ]:
#Busqueda de nulos
nulos = df_total.isnull().sum()
print(nulos)

porcentaje_nulos = (df_total.isnull().sum() / len(df_total)) * 100

print(porcentaje_nulos.sort_values(ascending=False))

name                         0
position                     0
overall                      0
potential                15845
value_eur                18562
wage_eur                 18193
age                          0
height_cm                15845
weight_kg                15845
league_name              18201
league_level             18586
club                      2356
nation                       0
preferred_foot               0
weak_foot                    0
skill_moves                  0
pace                     34397
shooting                 34397
passing                  34397
dribbling                34397
defending                34397
physicality              34397
movement_acceleration        0
movement_sprint_speed        0
power_stamina                0
year                         0
dtype: int64
shooting                 10.596800
pace                     10.596800
passing                  10.596800
dribbling                10.596800
defending                10.596800
physicality              10.596800
league_level              5.725852
value_eur                 5.718458
league_name               5.607243
wage_eur                  5.604779
potential                 4.881423
weight_kg                 4.881423
height_cm                 4.881423
club                      0.725821
age                       0.000000
overall                   0.000000
name                      0.000000
position                  0.000000
weak_foot                 0.000000
skill_moves               0.000000
nation                    0.000000
preferred_foot            0.000000
movement_acceleration     0.000000
movement_sprint_speed     0.000000
power_stamina             0.000000
year                      0.000000
dtype: float64

In [ ]:
#Reporte de nulos
reporte_nulos = pd.DataFrame({
    "columna": df_total.columns,
    "nulos": df_total.isnull().sum(),
    "porcentaje": (df_total.isnull().sum() / len(df_total)) * 100
})

reporte_nulos = reporte_nulos.sort_values("porcentaje", ascending=False)

reporte_nulos

                                     columna  nulos  porcentaje
shooting                            shooting  34397   10.596800
pace                                    pace  34397   10.596800
passing                              passing  34397   10.596800
dribbling                          dribbling  34397   10.596800
defending                          defending  34397   10.596800
physicality                      physicality  34397   10.596800
league_level                    league_level  18586    5.725852
value_eur                          value_eur  18562    5.718458
league_name                      league_name  18201    5.607243
wage_eur                            wage_eur  18193    5.604779
potential                          potential  15845    4.881423
weight_kg                          weight_kg  15845    4.881423
height_cm                          height_cm  15845    4.881423
club                                    club   2356    0.725821
age                                      age      0    0.000000
overall                              overall      0    0.000000
name                                    name      0    0.000000
position                            position      0    0.000000
weak_foot                          weak_foot      0    0.000000
skill_moves                      skill_moves      0    0.000000
nation                                nation      0    0.000000
preferred_foot                preferred_foot      0    0.000000
movement_acceleration  movement_acceleration      0    0.000000
movement_sprint_speed  movement_sprint_speed      0    0.000000
power_stamina                  power_stamina      0    0.000000
year                                    year      0    0.000000

In [ ]:
#Nulos de peso y altura se busca al jugador en otros años y se copia la misma
df_total = df_total.sort_values(["name", "year"])

df_total["height_cm"] = df_total.groupby("name")["height_cm"].transform(lambda x: x.ffill().bfill())
df_total["weight_kg"] = df_total.groupby("name")["weight_kg"].transform(lambda x: x.ffill().bfill())

/tmp/ipykernel_285/3039374363.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_total["height_cm"] = df_total.groupby("name")["height_cm"].transform(lambda x: x.ffill().bfill())
/tmp/ipykernel_285/3039374363.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_total["weight_kg"] = df_total.groupby("name")["weight_kg"].transform(lambda x: x.ffill().bfill())

In [ ]:
#Precio mercado y valor del jugador se saca con la mediana
df_total["value_eur"] = df_total["value_eur"].fillna(df_total["value_eur"].median())
df_total["wage_eur"] = df_total["wage_eur"].fillna(df_total["wage_eur"].median())

In [ ]:
#Busqueda de los nulos por posición:
stats = [
"pace",
"shooting",
"passing",
"dribbling",
"defending",
"physicality"
]

df_total[df_total[stats].isnull().any(axis=1)]["position"].value_counts()

position
GK                  34397
RB, CM, RM, ST          0
RB, CM, RM, LM          0
RB, CM, RM, CB          0
RB, CM, RM              0
                    ...
CM, RB, RWB, CDM        0
CM, RB, RWB             0
CM, RB, RW              0
CM, RB, RM, LM          0
CM, RM, LB              0
Name: count, Length: 2033, dtype: int64

In [ ]:
#Se analizó que los nulos eran de porteros, entonces se les coloca 0
df_total.loc[df_total["position"] == "GK", stats] = 0

In [ ]:
#Se imputa el potencial con respecto al overall
df_total["potential"] = df_total.groupby("overall")["potential"].transform(
    lambda x: x.fillna(x.median())
)

In [ ]:
#Cada club pertenece a una liga entonces se hace un busqueda para rellenar el nombre de la liga:
club_league_map = df_total.groupby("club")["league_name"].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)

df_total["league_name"] = df_total["league_name"].fillna(df_total["club"].map(club_league_map))

/tmp/ipykernel_285/812470194.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  club_league_map = df_total.groupby("club")["league_name"].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)

In [ ]:
#Misma lógica para el league_level
club_level_map = df_total.groupby("club")["league_level"].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)

df_total["league_level"] = df_total["league_level"].fillna(df_total["club"].map(club_level_map))

/tmp/ipykernel_285/1113371647.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  club_level_map = df_total.groupby("club")["league_level"].agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)

In [ ]:
nulos = df_total.isnull().sum()
print(nulos)

(df_total.isnull().sum() / len(df_total)) * 100

name                         0
position                     0
overall                      0
potential                    0
value_eur                    0
wage_eur                     0
age                          0
height_cm                13692
weight_kg                13692
league_name               7140
league_level              7140
club                         0
nation                       0
preferred_foot               0
weak_foot                    0
skill_moves                  0
pace                         0
shooting                     0
passing                      0
dribbling                    0
defending                    0
physicality                  0
movement_acceleration        0
movement_sprint_speed        0
power_stamina                0
year                         0
dtype: int64

name                     0.000000
position                 0.000000
overall                  0.000000
potential                0.000000
value_eur                0.000000
wage_eur                 0.000000
age                      0.000000
height_cm                4.218141
weight_kg                4.218141
league_name              2.199644
league_level             2.199644
club                     0.000000
nation                   0.000000
preferred_foot           0.000000
weak_foot                0.000000
skill_moves              0.000000
pace                     0.000000
shooting                 0.000000
passing                  0.000000
dribbling                0.000000
defending                0.000000
physicality              0.000000
movement_acceleration    0.000000
movement_sprint_speed    0.000000
power_stamina            0.000000
year                     0.000000
dtype: float64

In [ ]:
#A los jugadores que no se les encontró club se le coloca como agentes libres
df_total["club"] = df_total["club"].cat.add_categories("Free Agent")
df_total["club"] = df_total["club"].fillna("Free Agent")

In [ ]:
#Se vuelve a mapear el nombre de la liga y el nivel
df_total["league_name"] = df_total["league_name"].fillna(df_total["club"].map(club_league_map))
df_total["league_level"] = df_total["league_level"].fillna(df_total["club"].map(club_level_map))

In [ ]:
#Los jugadores que no se encontraron en años anteriores se les rellena la altura y peso con la mediana
df_total["height_cm"] = df_total["height_cm"].fillna(df_total["height_cm"].median())
df_total["weight_kg"] = df_total["weight_kg"].fillna(df_total["weight_kg"].median())

In [ ]:
#Las ligas que no se encontraron se les coloca Unknown
df_total["league_name"] = df_total["league_name"].cat.add_categories("Unknown")
df_total["league_name"] = df_total["league_name"].fillna("Unknown")

In [ ]:
#El nivel de la liga se llena con la moda
df_total["league_level"] = df_total["league_level"].fillna(
    df_total["league_level"].mode()[0]
)

In [ ]:
nulos = df_total.isnull().sum()
print(nulos)

(df_total.isnull().sum() / len(df_total)) * 100

name                     0
position                 0
overall                  0
potential                0
value_eur                0
wage_eur                 0
age                      0
height_cm                0
weight_kg                0
league_name              0
league_level             0
club                     0
nation                   0
preferred_foot           0
weak_foot                0
skill_moves              0
pace                     0
shooting                 0
passing                  0
dribbling                0
defending                0
physicality              0
movement_acceleration    0
movement_sprint_speed    0
power_stamina            0
year                     0
dtype: int64

name                     0.0
position                 0.0
overall                  0.0
potential                0.0
value_eur                0.0
wage_eur                 0.0
age                      0.0
height_cm                0.0
weight_kg                0.0
league_name              0.0
league_level             0.0
club                     0.0
nation                   0.0
preferred_foot           0.0
weak_foot                0.0
skill_moves              0.0
pace                     0.0
shooting                 0.0
passing                  0.0
dribbling                0.0
defending                0.0
physicality              0.0
movement_acceleration    0.0
movement_sprint_speed    0.0
power_stamina            0.0
year                     0.0
dtype: float64

In [ ]:
#Busqueda de duplicados
duplicados = df_total.duplicated().sum()

print("Filas duplicadas:", duplicados)

porcentaje_dup = (duplicados / len(df_total)) * 100

print("Porcentaje duplicados:", porcentaje_dup, "%")

Filas duplicadas: 0
Porcentaje duplicados: 0.0 %

In [ ]:
#Se analizó que muchos jugadores compartían el mismo nombre, entonces se optó por una busqueda de duplicados más especifica
df_total.duplicated(subset=["name","age","club","position","year"]).sum()

np.int64(0)

In [ ]:
df_total[df_total.duplicated(
    subset=["name","age","club","position","year"],
    keep=False
)].sort_values(["name","year"])

Empty DataFrame
Columns: [name, position, overall, potential, value_eur, wage_eur, age, height_cm, weight_kg, league_name, league_level, club, nation, preferred_foot, weak_foot, skill_moves, pace, shooting, passing, dribbling, defending, physicality, movement_acceleration, movement_sprint_speed, power_stamina, year]
Index: []

[0 rows x 26 columns]

In [ ]:
#Se eliminan duplicados por nombre, edad, club, position y año
df_total = df_total.drop_duplicates(
    subset=["name","age","club","position","year"],
    keep="first"
)

In [ ]:
#Verificación de duplicados
df_total.duplicated(
    subset=["name","age","club","position","year"]
).sum()

np.int64(0)

Preparación y Limpieza del Dataset
1. Selección de columnas relevantes

A partir de los datasets originales de FIFA (2015–2024), se realizó una selección de variables relevantes para el análisis. Se eliminaron columnas redundantes o poco útiles para el objetivo del proyecto, manteniendo únicamente atributos relacionados con:

Identificación del jugador

Características físicas

Habilidades técnicas

Información económica

Contexto competitivo (liga, club)

Año de registro

Las columnas finales seleccionadas fueron:

name, position, overall, potential, value_eur, wage_eur, age,
height_cm, weight_kg, league_name, league_level, club, nation,
preferred_foot, weak_foot, skill_moves, pace, shooting, passing,
dribbling, defending, physicality, movement_acceleration,
movement_sprint_speed, power_stamina, year

Esta selección permite mantener un dataset compacto pero informativo, adecuado para análisis estadístico y generación de variables derivadas.

2. Integración de datasets

Se cargaron los 9 archivos CSV correspondientes a las ediciones de FIFA entre 2015 y 2024 utilizando pandas y glob.

Durante este proceso:

Se añadió una columna year para identificar la temporada correspondiente.

Se estandarizaron los nombres de columnas para mantener consistencia entre los datasets.

Finalmente, todos los datasets fueron concatenados en una sola tabla unificada.

Esto permitió construir un dataset longitudinal de jugadores a través de múltiples temporadas.

3. Tipado de variables

Se asignaron tipos de datos apropiados a cada variable para mejorar:

eficiencia de memoria

consistencia del dataset

claridad en el análisis

Las variables se clasificaron en:

Categóricas

name

position

club

nation

league_name

preferred_foot

Numéricas enteras

overall

potential

age

height_cm

weight_kg

weak_foot

skill_moves

league_level

year

Numéricas continuas

value_eur

wage_eur

4. Análisis de calidad de datos

Se realizó un análisis del dataset para identificar:

valores nulos

duplicados

inconsistencias estructurales

El porcentaje de valores faltantes se calculó mediante:

(df_total.isnull().sum() / len(df_total)) * 100

Esto permitió identificar columnas con datos incompletos y diseñar estrategias de imputación adecuadas.

5. Limpieza e imputación de valores nulos

Se aplicaron diferentes estrategias de imputación dependiendo del tipo de variable y su significado dentro del dataset.

Variables físicas

Las columnas height_cm y weight_kg se imputaron inicialmente utilizando información histórica del mismo jugador en diferentes años.
Cuando no existía información disponible, se utilizó la mediana global de la variable para completar los valores faltantes.

Variables económicas

Las variables value_eur y wage_eur presentan una distribución con alta presencia de outliers, por lo que se utilizó la mediana como método de imputación para evitar sesgos.

Potencial del jugador

Los valores faltantes de potential se imputaron utilizando la mediana dentro de grupos de overall, debido a la fuerte relación existente entre ambas variables en el sistema de rating de FIFA.

Estadísticas de juego

Las columnas:

pace

shooting

passing

dribbling

defending

physicality

presentaban valores nulos principalmente en jugadores porteros (GK).
En estos casos se asignó el valor 0, ya que dichas estadísticas no aplican directamente a la posición de portero.

Información de liga

Para las variables:

league_name

league_level

se utilizó información del club del jugador para inferir los valores faltantes.
En los casos donde no fue posible inferir la liga, se asignó:

"Unknown" para league_name

la moda para league_level

6. Eliminación de duplicados

Debido a la integración de múltiples datasets, se detectaron registros duplicados.

Como el dataset no contiene un identificador único de jugador, se utilizó una clave compuesta para identificar duplicados:

(name, age, club, position, year)

Los registros duplicados fueron eliminados conservando la primera aparición de cada combinación.

7. Resultado final del proceso de limpieza

Después del proceso de limpieza:

Se eliminaron duplicados

Se imputaron valores faltantes

Se estandarizó el tipado de variables

El dataset final presenta:

0% de valores nulos en la mayoría de las variables

un porcentaje mínimo imputado en variables físicas y de liga

consistencia estructural entre todas las temporadas

Esto garantiza un dataset limpio, consistente y preparado para la etapa de análisis y generación de features derivados.